name: wtm-archive-viz
services:
  app:
    type: node
    port: '8000'
    build:
      - yarn install
tooling:
  yarn:
    service: app
  gatsby:
    service: app
  gatsby-develop:
    service: app
    description: Run gatsby develop command with necessary host arg to work with lando
    cmd:
      - gatsby develop --host 0.0.0.0
proxy:
  app:
    - wtm-archive-viz.lndo.site:8000
